[[redirects]]
  from = "/OneSignalSDKWorker.js"
  to = "/OneSignalSDKWorker.js"
  status = 200

[[redirects]]
  from = "/OneSignalSDKUpdaterWorker.js"
  to = "/OneSignalSDKUpdaterWorker.js"
  status = 200

[build]
  command = "echo 'Building site...'"
  functions = "netlify/functions"
  publish = "."

[[redirects]]
  from = "/card/:name"
  to = "/.netlify/functions/share-card?name=:name"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200