[build]
  command = "echo 'Building site...'"
  functions = "netlify/functions"
  publish = "."

[[redirects]]
  from = "/card/:name"
  to = "/.netlify/functions/share-card?name=:name"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/sw.js"
  to = "/sw.js"
  status = 200